### ISSUE TITLE
Todo April

### ISSUE THREAD

**Issue by EAT-CODE-KITE-REPEAT** [EAT-CODE-KITE-REPEAT/communify-js#1]
Make sure to use all endpoints available now in the correct way
- [x] updateProfile
- [x] changePassword
- [x] forgotPassword
- [x] members
- [x] profile

Query franchise
- [x] When in a franchise on xyz.communify.cc, do a franchise query in the saga and safe it to franchise on global
- [x] use that for /me query, login, signup, etc. 
- [x] on iOS/Android, don't look at subdomain but look at constants.franchise.id

Upload pictures
- [x] pick image/library 
- [x] resize on frontend
- [x] send base64 to backend
- [x] resize on backend to normal and thumbnail
- [x] save in folder
- [x] for signing up franchise
- [x] when signing up 
- [x] on update profile screen

Some styling
- [x] TextInputs better styling
- [ ] FranchiseAdmin better styling

Franchise
- [x] Make signup franchise form
- [x] Use this [Wildcards](https://vercel.com/blog/wildcard-domains)
- [x] Make created franchise available on {franchise}.communify.cc

Communities
- [x] For now, automatically create a community when creating franchise and keep it at one community per franchise

Posts
- [x] create backend
- [x] create frontend 
- [x] including picture upload

**Comment by EAT-CODE-KITE-REPEAT** [comment]
Improvements
- [ ] upload image on update profile screen
- [ ] admin -> update franchise screen with upload image
- [ ] Fix franchise admin

Communities
- [ ] POST /createCommunity
- [ ] POST /deleteCommunity
- [ ] POST /updateCommunity
- [ ] POST /setCommunity { coid, loginToken }
- [ ] GET /communities { fid }
- [ ] Create community screen
- [ ] admin -> update community screen
- [ ] choose community screen

Posts
- [ ] GET /posts?coid={coid}: post[]
- [ ] GET /post?coid={coid}&id={id}: {post,comments[] }
- [ ] POST /comment {loginToken, pid, message, image }
- [ ] POST /post {loginToken, message, image }
- [ ] POST /deletePost { loginToken, id }
- [ ] POST /deleteComment { loginToken, id }
- [ ] posts-screen
- [ ] post-screen (with comments)
- [ ] if logged, show comment section on posts screen and post screen
- [ ] include image upload 

Chat
- [ ] GET /channels?coid={coid} : Channel[]
- [ ] GET /channelsubs?loginToken={token} : Channel[] 
- [ ] GET /chat?id={cid} : chat[]
- [ ] POST /chat {loginToken, message}
- [ ] POST /channelsub { loginToken, cid }
- [ ] POST /deleteChannelsub { loginToken, cid }
- [ ] channel screen with all subbed channels, and button to add channel, and button to remove channel. clicking channel goes to chat screen
- [ ] chat screen with all chats

**Comment by EAT-CODE-KITE-REPEAT** [comment]
Then, 

- stripe integration and subscriptions
- paid and free posts
- different types of posts: article, youtube-video, image, etc.
- push notifications
- likes
- frontpage improvement
- questions per franchise

**Comment by EAT-CODE-KITE-REPEAT** [comment]
Communities implementation seems hard to do right, especially if you want all URL's to deeplink. And I want that, since I'm focussing on the web. Let's skip it for now, and focus on franchises

**Comment by EAT-CODE-KITE-REPEAT** [comment]
- [ ] Validate images [like this](https://stackoverflow.com/questions/53764734/how-do-i-validate-base64-images-in-nodejs-express)
- [ ] Add titles with Helmet
- [ ] Add favicon
- [ ] post title use slug; make this the url
- [ ] Remove cascades
- [ ] Add push notifications
- [ ] Add groups to posts
- [ ] Primary color, secondary color for franchises
- [ ] Improve frontpage
- [ ] put communify.cc on getcommunify.com instead as a backup
- [ ] Set live on Communify.cc

Resources
- [ ] Add resources tab
- [ ] Admin can create folders (with image or just folder icon)
- [ ] Folders can contain items of one kind per folder, so the folder is an audiofolder, a videofolder or an image folder
- [ ] Item can be audio, video (youtube) or image
- [ ] Resources tab can be turned on/off in admin panel
- [ ] Upload multiple files at once using DocumentPicker from expo
- [ ] Preview images, 
- [ ] view youtube videos in-app (https://forums.expo.io/t/expo-video-youtube/10241)
- [ ] Play audio in-app

**Comment by EAT-CODE-KITE-REPEAT** [comment]
Adding your own domain:
- [ ] create "add own domain" screen
- [ ] create endpoint updateDomain that adds the domain to ZEIT using their API, and removes the previously added domain if there is any, and sets domain of the franchise table to this value.
- [ ] make sure franchise endpoint also searches for domain
- [ ] make it impossible to find the homepage of communify on other domains.
- [ ] make it impossible to create communities with a DOT or other characters in the slug. remove those characters
- [ ] add instructions to set up domain

**Comment by EAT-CODE-KITE-REPEAT** [comment]
Bug:
- [ ] If you open a community for the first time, franchise object is still null when the page loads so you'll see "Community does not exist"

**Comment by EAT-CODE-KITE-REPEAT** [comment]
Auto-generate apps ?

It'd be great if you could create your own app for free. I can do this because I just need to run build:ios and build:android automatically and email the download links to the end-user. This will work for android ,but not for ios as the certificates won't match. So it's probably best to put even more focus on web. 

I could offer it for 200$ per month and do the first 10 apps a year for free.

**Comment by EAT-CODE-KITE-REPEAT** [comment]
Who is my following going to be? What is the target audience? What kind of community needs their own app?

**Comment by EAT-CODE-KITE-REPEAT** [comment]
Tribes
- [ ] CreateFranchise has to become createTribe
- [ ] Tribes model, CRUD { name, subtitle, description, image, thumbnail }
- [ ] Add a few example tribes
- [ ] Make sure to show them on tribes screen
- [ ] Make sure to show current tribe on tribescreen
- [ ] Make tribes clickable 


Chat
- [ ] GET /channels?coid={coid} : Channel[]
- [ ] GET /channelsubs?loginToken={token} : Channel[] 
- [ ] GET /chat?id={cid} : chat[]
- [ ] POST /chat {loginToken, message}
- [ ] POST /channelsub { loginToken, cid }
- [ ] POST /deleteChannelsub { loginToken, cid }
- [ ] channel screen with all subbed channels, and button to add channel, and button to remove channel. clicking channel goes to chat screen
- [ ] chat screen with all chats

Activities:
- [ ] Posts become activities
- [ ] Add date and location to every activity
- [ ] Add a few fake activities that look nice

Destinations
- [ ] Model, CRUD
- [ ] Add TravelLifeMovement, EAT CODE KITE REPEAT
- [ ] Show desitnations nicely according to UI
