### ISSUE TITLE
Todo May

### ISSUE THREAD

**Issue by EAT-CODE-KITE-REPEAT** [EAT-CODE-KITE-REPEAT/communify-js#2]
Use mysql
- [x] run process pm2 on server again
- [x] setup mysql similar to mcz

Tribes
- [x] CreateFranchise has to become createTribe
- [x] Tribes model, CRUD { name, subtitle, description, image, thumbnail }
- [x] Add a few example tribes
- [x] Make sure to show them on tribes screen
- [x] Make sure to show current tribe on tribescreen
- [x] Make tribes clickable 

Chat
- [ ] GET /channels?coid={coid} : Channel[]
- [ ] GET /channelsubs?loginToken={token} : Channel[] 
- [ ] GET /chat?id={cid} : chat[]
- [ ] POST /chat {loginToken, message}
- [ ] POST /channelsub { loginToken, cid }
- [ ] POST /deleteChannelsub { loginToken, cid }
- [ ] channel screen with all subbed channels, and button to add channel, and button to remove channel. clicking channel goes to chat screen
- [ ] chat screen with all chats

Activities:
- [ ] Posts become activities
- [ ] Add date and location to every activity
- [ ] Add a few fake activities that look nice

Destinations
- [ ] Model, CRUD
- [ ] Add TravelLifeMovement, EAT CODE KITE REPEAT destinations
- [ ] Show desitnations nicely according to UI
- [ ] Scrape all hostels in south east asia from hostelworld or booking
- [ ] Make it possible to add nonexisting hostel or hostel from list
- [ ] Show all destinations of a tribe on the tribepage

Map
- [ ] If you're in the tribe, on tribe page, choose between destinations , map, and members
- [ ] show a map with all members 
- [ ] Also show desitnations on the map

Set online
- [ ] Backpackingtribe.com {fid:1}
- [ ] Mynomadtribe.co {fid:2}
- [ ] Tribal.travel {fid:3}
